# Site settings
title: My log
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: #/blog/	# the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  KeachMurakami
encoding: utf-8

pygments: true
markdown: redcarpet
#redcarpet: 
#    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", 
#                 "tables", "with_toc_data"]